name: Release
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [win, mac, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          # Crucial for token propagation
          persist-credentials: true  
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # Add registry for proper auth
          registry-url: 'https://registry.npmjs.org'  

      - name: Install dependencies
        run: npm ci
        env:
          # Forward token to npm
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        run: npx electron-builder --${{ matrix.platforms }} --publish always
        env:
          # Use PAT instead of default token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          # Required for GitHub actions
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true